
message(STATUS "Fetching vcpkg deps")
find_package(redis++ CONFIG REQUIRED)
find_package(libuv CONFIG REQUIRED)
find_package(nlohmann_json CONFIG REQUIRED)
find_package(hiredis_ssl CONFIG REQUIRED)
find_package(hiredis CONFIG REQUIRED)
find_package(glm CONFIG REQUIRED)
find_package(GameNetworkingSockets CONFIG REQUIRED)
find_package(CURL REQUIRED)
find_package(ZLIB REQUIRED)
find_package(Boost REQUIRED COMPONENTS uuid)
find_package(Boost REQUIRED COMPONENTS stacktrace_addr2line)
find_package(Boost REQUIRED COMPONENTS multi_index)
find_package(Boost REQUIRED COMPONENTS type_traits)
find_package(Boost REQUIRED COMPONENTS describe)
find_package(Boost REQUIRED COMPONENTS container)
find_package(Boost REQUIRED COMPONENTS static_string)
