serverNodeName: ""

imagePullPolicy: IfNotPresent

images:
  watchdog: watchdog:latest
  proxy: proxy:latest
  shard: sandbox-server:latest
  cartograph: cartograph:latest
  internaldb: valkey/valkey-bundle:latest

cartograph:
  ingress:
    className: nginx
    host: cartograph.atlasnet.local
    path: /
    pathType: Prefix
